'use strict';

/**
 * Tool Registry — generates Python MCP modules for each provider at startup.
 * Modules are uploaded to workspace/tools/ and importable by subagents.
 *
 * Each module wraps provider APIs in typed Python functions with:
 * - Rate limiting via shared _rate_limiter.py
 * - Response caching (5-min TTL)
 * - Structured return types
 */

const fs = require('fs');
const path = require('path');
const serversConfig = require('../config/servers.json');

const OPENCLAW_DIR = process.env.OPENCLAW_DIR || '/root/openclaw';
const TOOLS_TEMPLATE_DIR = path.join(OPENCLAW_DIR, 'src/agent/tools/mcp');

/**
 * Generate all Python tool modules and upload to workspace tools/ directory.
 * @param {string} workspaceDir — target workspace directory
 */
async function generateToolModules(workspaceDir) {
  const toolsDir = path.join(workspaceDir, 'tools');
  const docsDir = path.join(toolsDir, 'docs');
  fs.mkdirSync(docsDir, { recursive: true });

  // Copy _rate_limiter.py and validate.py
  await generateRateLimiter(toolsDir);
  await generateValidator(toolsDir);

  // Generate per-provider modules
  for (const server of serversConfig.servers) {
    if (!server.enabled) continue;
    await generateProviderModule(server, toolsDir, docsDir);
  }

  console.log(`[registry] Tool modules generated in ${toolsDir}`);
}

async function generateRateLimiter(toolsDir) {
  const content = `# Auto-generated by registry.js — do not edit manually
import time, os, json, hashlib, sys

# Redis is optional — graceful fallback if unavailable
_r = None
try:
    import redis as _redis_lib
    _r = _redis_lib.Redis.from_url(
        os.environ.get("REDIS_URL", "redis://localhost:6379"),
        socket_connect_timeout=2, socket_timeout=2
    )
    _r.ping()  # test connection
except Exception:
    _r = None  # Redis unavailable — rate limiting disabled, no caching

def _acquire_token(provider: str, cost: int = 1) -> None:
    """Acquire a rate limit token. No-op if Redis is unavailable."""
    if _r is None:
        return  # No Redis — proceed without rate limiting
    bucket_key = f"rate_limit:{provider}"
    max_wait = 30  # Don't block more than 30s
    waited = 0
    while waited < max_wait:
        try:
            remaining = _r.get(bucket_key)
            if remaining is None or int(remaining) >= cost:
                if remaining is not None:
                    _r.decrby(bucket_key, cost)
                return
        except Exception:
            return  # Redis error — proceed
        time.sleep(0.5)
        waited += 0.5
    # Timed out waiting for token — proceed anyway to avoid hanging
    print(f"[rate_limiter] Warning: {provider} bucket wait timeout — proceeding")

def _cache_get(key: str):
    if _r is None:
        return None
    try:
        v = _r.get(f"cache:{key}")
        return json.loads(v) if v else None
    except Exception:
        return None

def _cache_set(key: str, value, ttl: int = 300):
    if _r is None:
        return
    try:
        _r.setex(f"cache:{key}", ttl, json.dumps(value))
    except Exception:
        pass

# ── Cycle-scoped cache ─────────────────────────────────────────────────────
# Cross-subagent dedup for the same daily cycle. CYCLE_ID is set by
# swarm.js (= LangGraph threadId). When unset (ad-hoc Discord tasks), the
# helpers are no-ops so behavior is identical to before.
#
# Different prefix (cycle:*) and longer TTL (24h) than the 5-min cache:* —
# do not pun on _cache_get/_cache_set.
#
# CYCLE_CACHE_DEBUG=1 logs HIT/MISS to stderr so a single cycle's hit rate
# can be greppable from the subagent stdout/stderr capture.

_CYCLE_TTL = 24 * 60 * 60
_CYCLE_DEBUG = os.environ.get("CYCLE_CACHE_DEBUG") == "1"

def _cycle_id() -> str:
    return os.environ.get("CYCLE_ID", "") or ""

def _cycle_key(scope: str, params) -> str:
    cid = _cycle_id()
    if not cid:
        return ""
    if isinstance(params, dict):
        norm = json.dumps(params, sort_keys=True, default=str)
    else:
        norm = str(params)
    h = hashlib.sha1(norm.encode("utf-8")).hexdigest()[:16]
    return f"cycle:{cid}:{scope}:{h}"

def _cycle_cache_get(scope: str, params):
    """Return cached value for (scope, params) within current cycle, else None.
    No-op when CYCLE_ID is unset or Redis is unavailable."""
    if _r is None:
        return None
    key = _cycle_key(scope, params)
    if not key:
        return None
    try:
        v = _r.get(key)
        if v is None:
            if _CYCLE_DEBUG: print(f"[cycle-cache] MISS {scope}", file=sys.stderr)
            return None
        if _CYCLE_DEBUG: print(f"[cycle-cache] HIT  {scope}", file=sys.stderr)
        return json.loads(v)
    except Exception:
        return None

def _cycle_cache_set(scope: str, params, value, ttl: int = _CYCLE_TTL):
    """Store value for (scope, params) within current cycle. No-op when
    CYCLE_ID is unset or Redis is unavailable."""
    if _r is None:
        return
    key = _cycle_key(scope, params)
    if not key:
        return
    try:
        _r.setex(key, ttl, json.dumps(value, default=str))
    except Exception:
        pass
`;
  fs.writeFileSync(path.join(toolsDir, '_rate_limiter.py'), content);
}

async function generateValidator(toolsDir) {
  const content = `# Auto-generated by registry.js — do not edit manually
import os, json
import pandas as pd

REQUIRED_SCHEMA = {
    "financials.csv": ["ticker", "date", "revenue", "grossProfit", "ebitda", "netIncome"],
    "comps.csv":      ["ticker", "evRevenue", "evEbitda", "pe", "revenueGrowth", "grossMargin"],
    "prices.parquet": ["date", "open", "high", "low", "close", "volume"],
}

ANOMALY_RULES = [
    ("revenue",      lambda x: x > 0,           "revenue is zero or negative"),
    ("grossMargin",  lambda x: -1 < x < 1,       "grossMargin out of [-100%, 100%] range"),
    ("evRevenue",    lambda x: x > 0,             "evRevenue is negative"),
]

def validate_manifest(task_dir: str) -> dict:
    """Validate DATA_MANIFEST.json and listed files. Returns {status, errors}."""
    manifest_path = os.path.join(task_dir, "data", "DATA_MANIFEST.json")
    if not os.path.exists(manifest_path):
        return {"status": "FAIL", "errors": ["DATA_MANIFEST.json not found"]}
    with open(manifest_path) as f:
        manifest = json.load(f)
    errors = []
    for fname, schema in REQUIRED_SCHEMA.items():
        fpath = os.path.join(task_dir, "data", fname)
        if fname not in manifest.get("files", {}):
            continue  # not required for this task
        if not os.path.exists(fpath):
            errors.append(f"{fname} listed in manifest but not found on disk")
            continue
        try:
            if fname.endswith(".parquet"):
                df = pd.read_parquet(fpath)
            else:
                df = pd.read_csv(fpath)
            for col in schema:
                if col not in df.columns:
                    errors.append(f"{fname} missing required column: {col}")
            for col, rule, msg in ANOMALY_RULES:
                if col in df.columns and not df[col].apply(rule).all():
                    errors.append(f"{fname}:{col} — {msg}")
        except Exception as e:
            errors.append(f"{fname} could not be read: {e}")
    return {"status": "FAIL" if errors else "PASS", "errors": errors}
`;
  fs.writeFileSync(path.join(toolsDir, 'validate.py'), content);
}

async function generateProviderModule(server, toolsDir, docsDir) {
  const templateFile = path.join(TOOLS_TEMPLATE_DIR, `${server.name}.js`);
  let template = '';

  if (fs.existsSync(templateFile)) {
    // JS file exports a generatePython() function
    const mod = require(templateFile);
    template = mod.generatePython ? mod.generatePython(server) : mod.pythonTemplate || '';
  }

  if (!template) {
    template = generateGenericModule(server);
  }

  fs.writeFileSync(path.join(toolsDir, `${server.name}.py`), template);

  // Generate docs
  const doc = `# ${server.name} Tool Module\n\n${server.description}\n\n**Import:** \`${server.import_path}\`\n\n**Tier:** ${server.tier} | **Fallback:** ${server.fallback || 'none'}\n`;
  fs.writeFileSync(path.join(docsDir, `${server.name}.md`), doc);
}

function generateGenericModule(server) {
  return `# Auto-generated by registry.js — ${server.name}
# ${server.description}
import os, json, requests
from _rate_limiter import _acquire_token

_API_KEY = os.environ.get("${server.name.toUpperCase().replace('-', '_')}_API_KEY", "")
_PROVIDER = "${server.name}"

def _get(url: str, params: dict = None) -> dict:
    _acquire_token(_PROVIDER)
    r = requests.get(url, params=params or {}, timeout=30)
    r.raise_for_status()
    return r.json()
`;
}

module.exports = { generateToolModules };
