/**
 * Deployment Gate
 *
 * Governs SUBAGENT spawning only (swarm.init calls).
 * BotJohn himself is the master PM agent and is always permitted to respond
 * to any message — this gate does not apply to his direct responses.
 *
 * Permitted subagent activations:
 *   DEPLOY  — strategist writes + validates + registers a strategy file
 *   REPORT  — report-builder generates performance report for a deployed strategy
 *   SIGNAL_PROCESSING — compute/equity-analyst/research processing a confluence candidate
 *   MARKET_STATE — data-prep running the scheduled market state update
 *   RISK_SCAN — emergency strategist scan (bypasses off-hours/budget constraints)
 *
 * Blocked subagent activations:
 *   - research invoked directly (not via signal processing pipeline)
 *   - data-prep in TIER_A or TIER_B mode (deprecated)
 *   - any prompt containing deprecated patterns (fetch data, run signals, etc.)
 */

'use strict';

const PERMITTED_MODES = new Set(['DEPLOY', 'REPORT']);

// Map of phrases that sound like agent work but aren't permitted
const BLOCKED_PATTERNS = [
    { pattern: /run.{0,20}signal/i,       reason: 'Signal execution runs via cron (signal_runner.py). No LLM needed.' },
    { pattern: /generate.{0,20}signal/i,  reason: 'Signal generation is handled by hardcoded Python strategies. No LLM needed.' },
    { pattern: /check.{0,20}signal/i,     reason: "Use /signals in Discord to see today's signal output." },
    { pattern: /build.{0,20}cache/i,      reason: 'Cache builds automatically during market-state run. No LLM needed.' },
    { pattern: /fetch.{0,20}data/i,       reason: 'Data fetching runs in the market-state pipeline. No LLM needed.' },
    { pattern: /update.{0,20}price/i,     reason: 'Prices update via master_dataset.py on schedule. No LLM needed.' },
    { pattern: /score.{0,20}confluence/i, reason: 'Confluence scoring runs in signal_runner.py. No LLM needed.' },
    { pattern: /run.{0,20}backtest/i,     reason: 'Backtests run via the strategist agent in off-hours DEPLOY mode.' },
    { pattern: /diligence/i,              reason: 'Individual diligence runs are superseded by the zero-token signal engine. Use /signals.' },
    { pattern: /research.{0,20}ticker/i,  reason: 'Per-ticker research is no longer an agent task. Signals come from the strategy library.' },
];

/**
 * Validate that an agent invocation is permitted.
 * Returns { allowed: true, effective_mode } or { allowed: false, reason }
 */
function validateInvocation(agentType, mode, prompt) {

    // PM_TASK mode — BotJohn (master PM agent) handling a general message.
    // Always permitted. Must be checked first, before any agent-type rules.
    // The constraint is on pipeline automation, not on BotJohn's own responses.
    if (mode === 'PM_TASK') {
        return { allowed: true, effective_mode: 'PM_TASK' };
    }

    // Strategist in off-hours is always DEPLOY mode
    if (agentType === 'strategist') {
        if (!mode || mode === 'EXPLORE' || mode === 'BACKTEST' || mode === 'VALIDATE') {
            return { allowed: true, effective_mode: 'DEPLOY' };
        }
        if (mode === 'RISK_SCAN') {
            return { allowed: true, effective_mode: 'RISK_SCAN' };
        }
        if (mode === 'REPORT') {
            return { allowed: true, effective_mode: 'REPORT' };
        }
    }

    // Report-builder: only permitted in REPORT mode
    if (agentType === 'report-builder') {
        const reportMode = mode || 'TRADE';
        if (['REPORT', 'STRATEGY_PERFORMANCE', 'TRADE'].includes(reportMode)) {
            return { allowed: true, effective_mode: 'REPORT' };
        }
        return {
            allowed: false,
            reason: `report-builder only permitted for REPORT, STRATEGY_PERFORMANCE, or TRADE. Got: ${reportMode}`,
        };
    }

    // Compute + equity-analyst: only when processing a pre-computed confluence candidate
    if (agentType === 'compute' || agentType === 'equity-analyst') {
        if (!mode || mode === 'SIGNAL_PROCESSING') {
            return { allowed: true, effective_mode: 'SIGNAL_PROCESSING' };
        }
        return {
            allowed: false,
            reason: `${agentType} only runs when processing a pre-computed confluence candidate from the signal runner. Mode must be SIGNAL_PROCESSING.`,
        };
    }

    // Research agent: blocked unless invoked by signal processing pipeline or BotJohn PM
    if (agentType === 'research') {
        if (mode === 'SIGNAL_PROCESSING') {
            return { allowed: true, effective_mode: 'SIGNAL_PROCESSING' };
        }
        return {
            allowed: false,
            reason: [
                'Direct research invocation is no longer permitted.',
                'Per-ticker research is superseded by the zero-token signal engine.',
                'Signals are generated by hardcoded Python strategies from the master dataset.',
                'The research agent only activates when processing a pre-computed confluence candidate.',
                "To see today's signals: /signals",
                'To deploy a new strategy: /deploy-strategy {description}',
                'To see a strategy report: /strategy-report {id}',
            ].join('\n'),
        };
    }

    // Data-prep: only permitted in MARKET_STATE mode (scheduled, not manually invoked)
    if (agentType === 'data-prep') {
        if (mode === 'MARKET_STATE') {
            return { allowed: true, effective_mode: 'MARKET_STATE' };
        }
        if (mode === 'TIER_A' || mode === 'TIER_B') {
            return {
                allowed: false,
                reason: `TIER_A and TIER_B data-prep modes are deprecated. Signal generation now runs via the zero-token signal engine. Use MARKET_STATE mode only, triggered by the daily schedule.`,
            };
        }
        return {
            allowed: false,
            reason: `data-prep only runs in MARKET_STATE mode on schedule. Manual invocation is not permitted. The daily cron at 16:15 ET handles this.`,
        };
    }

    // Check prompt content for blocked patterns
    if (prompt) {
        for (const { pattern, reason } of BLOCKED_PATTERNS) {
            if (pattern.test(prompt)) {
                return { allowed: false, reason };
            }
        }
    }

    return { allowed: true, effective_mode: mode || 'UNKNOWN' };
}

/**
 * Gate function — throws DeploymentGateError if not permitted.
 * Returns effective_mode string on success.
 */
function deploymentGateMiddleware(agentType, mode, prompt) {
    const result = validateInvocation(agentType, mode, prompt);
    if (!result.allowed) {
        throw new DeploymentGateError(result.reason);
    }
    return result.effective_mode;
}

class DeploymentGateError extends Error {
    constructor(reason) {
        super(reason);
        this.name = 'DeploymentGateError';
        this.code = 'AGENT_NOT_PERMITTED';
    }
}

module.exports = { validateInvocation, deploymentGateMiddleware, DeploymentGateError };
