-- Strategy registry: all approved hardcoded strategies
CREATE TABLE strategy_registry (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    tier INTEGER,
    hypothesis_id UUID REFERENCES strategy_hypotheses(id) ON DELETE SET NULL,
    implementation_path TEXT NOT NULL,
    parameters JSONB DEFAULT '{}',
    regime_conditions JSONB DEFAULT '{}',
    universe TEXT[] DEFAULT ARRAY['SP100'],
    signal_frequency TEXT DEFAULT 'daily',
    status TEXT DEFAULT 'pending_approval',
    approved_by TEXT,
    approved_at TIMESTAMPTZ,
    deprecated_at TIMESTAMPTZ,
    deprecation_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    backtest_sharpe NUMERIC,
    backtest_return_pct NUMERIC,
    backtest_max_dd_pct NUMERIC,
    live_days INTEGER DEFAULT 0,
    live_sharpe NUMERIC,
    live_return_pct NUMERIC
);

-- Live signals generated by execution engine (no LLM involved)
CREATE TABLE execution_signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    strategy_id TEXT REFERENCES strategy_registry(id),
    workspace_id UUID REFERENCES workspaces(id),
    signal_date DATE NOT NULL,
    ticker TEXT,
    direction TEXT NOT NULL,
    entry_price NUMERIC,
    stop_loss NUMERIC,
    target_1 NUMERIC,
    target_2 NUMERIC,
    target_3 NUMERIC,
    position_size_pct NUMERIC,
    regime_state TEXT,
    signal_params JSONB DEFAULT '{}',
    confluence_strategies TEXT[],
    confluence_count INTEGER DEFAULT 1,
    status TEXT DEFAULT 'open',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(strategy_id, signal_date, ticker, direction)
);

-- P&L tracking: updated daily by execution engine
CREATE TABLE signal_pnl (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    signal_id UUID REFERENCES execution_signals(id),
    strategy_id TEXT REFERENCES strategy_registry(id),
    workspace_id UUID REFERENCES workspaces(id),
    pnl_date DATE NOT NULL,
    close_price NUMERIC,
    unrealized_pnl_pct NUMERIC,
    days_held INTEGER DEFAULT 0,
    status TEXT DEFAULT 'open',
    closed_price NUMERIC,
    closed_at DATE,
    close_reason TEXT,
    realized_pnl_pct NUMERIC,
    UNIQUE(signal_id, pnl_date)
);

-- Report triggers: queue for strategist to review
CREATE TABLE report_triggers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    strategy_id TEXT REFERENCES strategy_registry(id),
    workspace_id UUID REFERENCES workspaces(id),
    trigger_type TEXT NOT NULL,
    trigger_reason TEXT NOT NULL,
    triggered_at TIMESTAMPTZ DEFAULT NOW(),
    processed BOOLEAN DEFAULT FALSE,
    processed_at TIMESTAMPTZ,
    report_path TEXT
);

-- Execution run log: one row per daily engine run
CREATE TABLE execution_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID REFERENCES workspaces(id),
    run_date DATE NOT NULL,
    regime_state TEXT,
    strategies_run INTEGER DEFAULT 0,
    signals_generated INTEGER DEFAULT 0,
    high_confluence_signals INTEGER DEFAULT 0,
    pnl_updates INTEGER DEFAULT 0,
    report_triggers_fired INTEGER DEFAULT 0,
    duration_seconds NUMERIC,
    errors JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Cross-strategy confluence: tracks when multiple strategies agree
CREATE TABLE confluence_signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID REFERENCES workspaces(id),
    signal_date DATE NOT NULL,
    ticker TEXT NOT NULL,
    direction TEXT NOT NULL,
    agreeing_strategies TEXT[] NOT NULL,
    confluence_count INTEGER NOT NULL,
    regime_state TEXT,
    combined_size_pct NUMERIC,
    investigation_queued BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(workspace_id, signal_date, ticker, direction)
);

-- Indexes
CREATE INDEX idx_execution_signals_date     ON execution_signals(signal_date DESC);
CREATE INDEX idx_execution_signals_strategy ON execution_signals(strategy_id);
CREATE INDEX idx_execution_signals_status   ON execution_signals(status);
CREATE INDEX idx_signal_pnl_date            ON signal_pnl(pnl_date DESC);
CREATE INDEX idx_signal_pnl_signal          ON signal_pnl(signal_id);
CREATE INDEX idx_report_triggers_processed  ON report_triggers(processed);
CREATE INDEX idx_confluence_signals_date    ON confluence_signals(signal_date DESC);
CREATE INDEX idx_confluence_signals_count   ON confluence_signals(confluence_count DESC);
CREATE INDEX idx_strategy_registry_status   ON strategy_registry(status);
