-- Version history for each strategy
-- Each deployment of a strategy creates a new version row.
-- The original file is never modified.

CREATE TABLE strategy_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID REFERENCES workspaces(id),
    strategy_id TEXT NOT NULL,                 -- base ID, e.g. 'MV01_momentum_value'
    version INTEGER NOT NULL DEFAULT 1,
    versioned_id TEXT NOT NULL UNIQUE,         -- 'MV01_momentum_value_v1', 'MV01_momentum_value_v2'
    file_path TEXT NOT NULL,
    params JSONB DEFAULT '{}',                 -- parameter snapshot at this version
    param_changes JSONB DEFAULT '{}',          -- what changed vs prior version
    change_reason TEXT,                        -- why the parameters were changed
    deployed_at TIMESTAMPTZ DEFAULT NOW(),
    deployed_by TEXT DEFAULT 'operator',
    validation_passed BOOLEAN NOT NULL,
    validation_report JSONB,
    is_active BOOLEAN DEFAULT TRUE,            -- only one version active per strategy_id
    superseded_at TIMESTAMPTZ,                 -- when this version was replaced
    superseded_by TEXT,                        -- versioned_id that replaced it
    signal_count INTEGER DEFAULT 0,            -- signals generated by this version
    notes TEXT
);

CREATE INDEX idx_strategy_versions_base ON strategy_versions(strategy_id);
CREATE INDEX idx_strategy_versions_active ON strategy_versions(strategy_id) WHERE is_active = TRUE;
CREATE INDEX idx_strategy_versions_versioned ON strategy_versions(versioned_id);

-- Add version tracking to execution_signals so we know which version fired
ALTER TABLE execution_signals ADD COLUMN IF NOT EXISTS strategy_version TEXT;

-- Add version tracking to signal_pnl
ALTER TABLE signal_pnl ADD COLUMN IF NOT EXISTS strategy_version TEXT;
