-- 065_replace_researchdesk_with_mastermind.sql
--
-- Replace the retired `researchdesk` agent persona with `mastermind`.
-- ResearchJohn / ResearchDesk was deleted 2026-05-02. MastermindJohn
-- (Opus 4.7) now owns both #research-feed and #strategy-memos channels.
-- Webhook URLs in webhook_urls JSONB are regenerated by initWebhooks()
-- on next johnbot startup, so we explicitly clear them here to avoid
-- accidental cross-posts before regeneration.
--
-- Idempotent: safe to re-run.

INSERT INTO agent_registry
  (id, display_name, emoji, model, description, channel_keys, status, webhook_urls)
VALUES
  ('mastermind',
   '🧠 MastermindJohn',
   '🧠',
   'claude-opus-4-7',
   'Research curator & strategy reviewer',
   ARRAY['research-feed', 'strategy-memos'],
   'offline',
   '{}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  emoji        = EXCLUDED.emoji,
  model        = EXCLUDED.model,
  description  = EXCLUDED.description,
  channel_keys = EXCLUDED.channel_keys;

DELETE FROM agent_registry WHERE id = 'researchdesk';
