-- 086_mastermind_prompt_addenda.sql
-- Phase 2F: operator-approved text addenda that get prepended to the
-- Mastermind comprehensive-review prompt. Two sources:
--   'auto:bias_detector' — generated by mastermind_recalibration when a
--     confidence bucket diverges from its midpoint by > BIAS_DELTA_THRESHOLD
--     with >= MIN_BUCKET_SAMPLES observations. Inserted as 'pending'; needs
--     operator approval to flip to 'active'.
--   'operator:<name>' — manually authored. Inserted directly as 'active'.
--
-- Status transitions:
--   pending → active   (operator approves)
--   pending → rejected (operator declines)
--   active  → expired  (past valid_until; auto-flipped on read)
--   active  → superseded (newer addendum replaces; supersedes_id back-ref)
--
-- Append-only per CLAUDE.md invariant. No DELETE path.
--
-- Spec: docs/superpowers/specs/2026-05-13-regime-blended-sizer-phase-2f-design.md

CREATE TABLE IF NOT EXISTS mastermind_prompt_addenda (
    id              BIGSERIAL    PRIMARY KEY,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    source          TEXT         NOT NULL,
    triggered_by    JSONB,
    addendum_text   TEXT         NOT NULL,
    rationale       TEXT,
    valid_from      TIMESTAMPTZ,
    valid_until     TIMESTAMPTZ,
    status          TEXT         NOT NULL DEFAULT 'pending',
    decided_at      TIMESTAMPTZ,
    decided_by      TEXT,
    decision_reason TEXT,
    supersedes_id   BIGINT REFERENCES mastermind_prompt_addenda(id)
);

CREATE INDEX IF NOT EXISTS idx_mpa_status_created
    ON mastermind_prompt_addenda (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_mpa_active_window
    ON mastermind_prompt_addenda (status, valid_until)
 WHERE status = 'active';
