'use strict';
// tests/test_activation_api.test.js — activation_preview.js: the parser
// behind POST /api/activation/dry-run, plus the pure GET/PUT helpers behind
// /api/config/activation-min-sharpe (Task 2, spec docs/specs/2026-09-25-
// activation-bench-relative-spec.md §3 — the min-Sharpe SLIDER control is
// removed; this path is now read-only). Pure, no DB / no server boot: none
// of this requires src/channels/api/server.js (mirrors tests/test_blend_
// scope.js and this file's own pre-rename docstring). Renamed from
// tests/test_activation_slider_api.js (git mv) so `.test.js` puts it in
// `npm run test:js`'s glob — it previously was NOT auto-run.
//
// The FIXTURE below is AUTHENTIC assigner output: the HEADER/DETAIL/SUMMARY
// lines were generated by driving the real src/backtest/activation_
// assigner.py _log/_fmt_diff helpers plus main()'s verbatim header/summary
// f-strings over synthetic results (2026-07-11); the bench/bench-diff lines
// (Task 1, wired up here in Task 2) were generated 2026-09-25 via
// `PYTHONPATH=src python3 -c "from backtest import activation_assigner as
// aa; print(aa._fmt_bench_vector(...)); print(aa._fmt_bench_diff(...))"` —
// pure functions, no DB touched. If the assigner's print format changes,
// regenerate rather than editing lines in place.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {
  parseActivationDryRun, CANONICAL_REGIMES,
  benchCardPayload, minSharpeGone, MIN_SHARPE_GONE_BODY,
  clampExcessValue, excessCardPayload,
  ACTIVATION_EXCESS_MIN, ACTIVATION_EXCESS_MAX, ACTIVATION_EXCESS_DEFAULT,
} = require('../src/channels/api/activation_preview');

const SERVER_JS = path.join(__dirname, '../src/channels/api/server.js');

const FIXTURE = `[activation_assigner] threshold=1.85 min_trades=20 dry_run=True strategies=6
[activation_assigner]   ERROR S_zeta_broken: relation 'strategy_backtest_regimes' scan failed
[activation_assigner]   S_alpha_momo: LOW_VOL: True->False (deactivated), TRANSITIONING: None->False (initialized), HIGH_VOL: False->False, CRISIS: True->False (deactivated)
[activation_assigner]   S_beta_meanrev: LOW_VOL: True->True, TRANSITIONING: False->False, HIGH_VOL: False->True (activated), CRISIS: None->False (initialized)
[activation_assigner]   S_gamma_carry: LOW_VOL: False->False, TRANSITIONING: False->False, HIGH_VOL: True->True, CRISIS: True->True
[activation_assigner]   S_delta_pairs: LOW_VOL: None->False (initialized), TRANSITIONING: True->False (deactivated), HIGH_VOL: None->False (initialized), CRISIS: None->False (initialized)
[activation_assigner]   SKIP  S_eps_nodata: no primary_window backtest with regime rows
[activation_assigner] activation_assigner summary: 4 strategies evaluated, 1 skipped (no corrected backtest), 1 cell(s) activated, 3 cell(s) deactivated, 2 newly-dormant strategies (S_alpha_momo, S_delta_pairs), threshold=1.85, min_trades=20, dry_run=True, errors=1
`;

// ── parseActivationDryRun ────────────────────────────────────────────────
test('full authentic transcript — summary-backed fields + per-regime counts', () => {
  const p = parseActivationDryRun(FIXTURE);
  assert.equal(p.summary_found, true);
  assert.equal(p.threshold, 1.85);
  assert.equal(p.min_trades, 20);
  assert.equal(p.evaluated, 4);
  assert.equal(p.skipped, 1);
  assert.equal(p.errors, 1);
  assert.deepEqual(p.cells, { activated: 1, deactivated: 3 });
  assert.deepEqual(p.newly_dormant, ['S_alpha_momo', 'S_delta_pairs']);
  assert.equal(p.newly_dormant_count, 2);
  assert.deepEqual(p.warnings, []);

  // Per-regime: eligible_now = prior True count (DB reality),
  // eligible_preview = new True count (hypothetical).
  assert.deepEqual(p.per_regime.LOW_VOL,
    { eligible_now: 2, eligible_preview: 1, dormant_preview: 3,
      activated: 0, deactivated: 1, initialized: 1, unchanged: 2 });
  assert.deepEqual(p.per_regime.HIGH_VOL,
    { eligible_now: 1, eligible_preview: 2, dormant_preview: 2,
      activated: 1, deactivated: 0, initialized: 1, unchanged: 2 });
  assert.deepEqual(p.per_regime.CRISIS,
    { eligible_now: 2, eligible_preview: 1, dormant_preview: 3,
      activated: 0, deactivated: 1, initialized: 2, unchanged: 1 });

  // changed_strategies excludes the fully-unchanged S_gamma_carry.
  assert.deepEqual(p.changed_strategies.map(s => s.strategy_id),
    ['S_alpha_momo', 'S_beta_meanrev', 'S_delta_pairs']);
  const alpha = p.changed_strategies[0];
  assert.equal(alpha.newly_dormant, true);
  assert.deepEqual(alpha.cells.TRANSITIONING,
    { before: null, after: false, action: 'initialized' });   // None → null
  assert.deepEqual(alpha.cells.LOW_VOL,
    { before: true, after: false, action: 'deactivated' });
  assert.equal(p.changed_strategies_truncated, false);
  assert.ok(p.summary_line.startsWith('[activation_assigner] activation_assigner summary:'));
  // No bench: / bench diff: lines in this fixture -- both fields null, not
  // absent/undefined (spec §5-E fields are always present on the object).
  assert.equal(p.bench, null);
  assert.equal(p.bench_diff, null);
});

test('singular newly-dormant grammar ("1 newly-dormant strategy (S_x)")', () => {
  const p = parseActivationDryRun(
    '[activation_assigner] threshold=0.5 min_trades=20 dry_run=True strategies=1\n' +
    '[activation_assigner]   S_x: LOW_VOL: True->False (deactivated), TRANSITIONING: False->False, HIGH_VOL: False->False, CRISIS: False->False\n' +
    '[activation_assigner] activation_assigner summary: 1 strategies evaluated, 0 skipped (no corrected backtest), 0 cell(s) activated, 1 cell(s) deactivated, 1 newly-dormant strategy (S_x), threshold=0.5, min_trades=20, dry_run=True, errors=0\n'
  );
  assert.equal(p.summary_found, true);
  assert.equal(p.newly_dormant_count, 1);
  assert.deepEqual(p.newly_dormant, ['S_x']);
  assert.deepEqual(p.warnings, []);
});

test('zero newly-dormant — the parenthesised list is omitted entirely', () => {
  const p = parseActivationDryRun(
    '[activation_assigner] threshold=0.5 min_trades=20 dry_run=True strategies=1\n' +
    '[activation_assigner]   S_y: LOW_VOL: False->True (activated), TRANSITIONING: False->False, HIGH_VOL: False->False, CRISIS: False->False\n' +
    '[activation_assigner] activation_assigner summary: 1 strategies evaluated, 0 skipped (no corrected backtest), 1 cell(s) activated, 0 cell(s) deactivated, 0 newly-dormant strategies, threshold=0.5, min_trades=20, dry_run=True, errors=0\n'
  );
  assert.equal(p.summary_found, true);
  assert.equal(p.newly_dormant_count, 0);
  assert.deepEqual(p.newly_dormant, []);
  assert.deepEqual(p.cells, { activated: 1, deactivated: 0 });
  assert.deepEqual(p.warnings, []);
});

test('truncated output (no summary line) falls back to per-line counts + warns; never throws', () => {
  const p = parseActivationDryRun(
    '[activation_assigner] threshold=0.5 min_trades=20 dry_run=True strategies=3\n' +
    '[activation_assigner]   S_a: LOW_VOL: True->False (deactivated), TRANSITIONING: False->False, HIGH_VOL: False->False, CRISIS: False->False\n' +
    '[activation_assigner]   SKIP  S_b: no primary_window backtest with regime rows\n'
  );
  assert.equal(p.summary_found, false);
  assert.equal(p.threshold, 0.5);   // falls back to header threshold
  assert.equal(p.min_trades, 20);
  assert.equal(p.evaluated, 1);     // falls back to detail-line count
  assert.equal(p.skipped, 1);
  assert.deepEqual(p.cells, { activated: 0, deactivated: 1 });
  assert.deepEqual(p.newly_dormant, ['S_a']);
  assert.equal(p.warnings.length, 1);
  assert.ok(/summary line not found/.test(p.warnings[0]));
});

test('garbage / empty input: structured zeros, no throw', () => {
  for (const junk of ['', null, undefined, 'POSTGRES_URI not set\nTraceback (most recent call last):\n  boom']) {
    const p = parseActivationDryRun(junk);
    assert.equal(p.summary_found, false);
    assert.equal(p.evaluated, 0);
    assert.deepEqual(p.newly_dormant, []);
    for (const r of CANONICAL_REGIMES) {
      assert.equal(p.per_regime[r].eligible_now, 0);
    }
  }
});

test('cross-check discrepancy (format drift guard): warnings surface it, summary wins for the headline', () => {
  const p = parseActivationDryRun(
    '[activation_assigner] threshold=0.5 min_trades=20 dry_run=True strategies=1\n' +
    '[activation_assigner]   S_a: LOW_VOL: True->True, TRANSITIONING: False->False, HIGH_VOL: False->False, CRISIS: False->False\n' +
    '[activation_assigner] activation_assigner summary: 1 strategies evaluated, 0 skipped (no corrected backtest), 4 cell(s) activated, 4 cell(s) deactivated, 1 newly-dormant strategy (S_ghost), threshold=0.5, min_trades=20, dry_run=True, errors=0\n'
  );
  assert.equal(p.summary_found, true);
  assert.ok(p.warnings.some(w => /newly-dormant mismatch/.test(w)));
  assert.ok(p.warnings.some(w => /cell-count mismatch/.test(w)));
  assert.deepEqual(p.newly_dormant, ['S_ghost']);   // summary list preferred when present
});

// ── bench: / bench diff: lines (spec §5-E, Task 1 output, Task 2 wiring) ──
// Generated 2026-09-25 via the real Python formatters (PYTHONPATH=src
// python3 -c "from backtest import activation_assigner as aa; ..."), no DB.
test('bench: line parses the sleeve id/source/run + per-regime vector', () => {
  const p = parseActivationDryRun(
    '[activation_assigner] bench: sleeve=S_beta_spy source=registry run=r51b5b915 LOW_VOL=0.95 TRANSITIONING=0.44 HIGH_VOL=0.53 CRISIS=1.58\n'
  );
  assert.deepEqual(p.bench, {
    sleeve_id: 'S_beta_spy', sleeve_source: 'registry', run_id: 'r51b5b915',
    values: { LOW_VOL: 0.95, TRANSITIONING: 0.44, HIGH_VOL: 0.53, CRISIS: 1.58 },
  });
});

test('bench: line with run=None (no sleeve backtest found) becomes run_id: null', () => {
  const p = parseActivationDryRun(
    '[activation_assigner] bench: sleeve=S_beta_spy source=literal_fallback run=None LOW_VOL=0.95 TRANSITIONING=0.44 HIGH_VOL=0.53 CRISIS=1.58\n'
  );
  assert.equal(p.bench.run_id, null);
  assert.equal(p.bench.sleeve_source, 'literal_fallback');
});

test('bench diff: line parses the per-regime gained/lost tally', () => {
  const p = parseActivationDryRun(
    '[activation_assigner] bench diff: LOW_VOL +4/-1 TRANSITIONING +7/-0 HIGH_VOL +12/-0 CRISIS +0/-14\n'
  );
  assert.deepEqual(p.bench_diff, {
    LOW_VOL:       { gained: 4,  lost: 1 },
    TRANSITIONING: { gained: 7,  lost: 0 },
    HIGH_VOL:      { gained: 12, lost: 0 },
    CRISIS:        { gained: 0,  lost: 14 },
  });
});

test('bench: / bench diff: lines never match HEADER/DETAIL/SUMMARY (no double-counting)', () => {
  // Full transcript with a bench line spliced in -- summary/detail counts
  // must be unaffected, and the bench line must not be picked up as a
  // detail/skip/error/header/summary line.
  const withBench = FIXTURE.replace(
    '[activation_assigner] activation_assigner summary:',
    '[activation_assigner] bench: sleeve=S_beta_spy source=registry run=r1 LOW_VOL=1.0 TRANSITIONING=1.0 HIGH_VOL=1.0 CRISIS=1.0\n' +
    '[activation_assigner] activation_assigner summary:'
  );
  const p = parseActivationDryRun(withBench);
  assert.equal(p.evaluated, 4);       // unchanged from the base fixture test
  assert.ok(p.bench);
  assert.equal(p.bench.sleeve_id, 'S_beta_spy');
});

// ── WARN: lines (F1-a, fix round 1) — degraded bench fallback (tier-2
// pipeline_config / tier-3 DEFAULT_MIN_SHARPE) previously fell through
// this parser silently and never reached the operator anywhere on the
// dashboard. Verbatim from activation_assigner.py's own _log(f'WARN: ...')
// call sites (load_bench_sharpe, tier-2/tier-3 fallback branches).
test('WARN: lines (tier-2 and tier-3 degraded bench fallback) are collected into warnings; no WARN -> empty', () => {
  const withWarns = FIXTURE.replace(
    '[activation_assigner] activation_assigner summary:',
    '[activation_assigner] WARN: CRISIS bench sharpe missing from sleeve run r51b5b915; using last-applied pipeline_config vector\n' +
    '[activation_assigner] WARN: HIGH_VOL bench sharpe unavailable (no sleeve run, no pipeline_config vector); using DEFAULT_MIN_SHARPE=0.5\n' +
    '[activation_assigner] activation_assigner summary:'
  );
  const p = parseActivationDryRun(withWarns);
  assert.equal(p.evaluated, 4);   // unaffected -- WARN lines aren't detail/skip/error lines
  assert.equal(p.warnings.length, 2);
  assert.ok(p.warnings.some(w => /^CRISIS bench sharpe missing from sleeve run r51b5b915/.test(w)));
  assert.ok(p.warnings.some(w => /^HIGH_VOL bench sharpe unavailable \(no sleeve run, no pipeline_config vector\); using DEFAULT_MIN_SHARPE=0\.5$/.test(w)));

  // No WARN lines at all -> warnings stays empty (the base FIXTURE test
  // above already asserts this too; repeated here to pair explicitly with
  // the WARN case per the brief).
  const clean = parseActivationDryRun(FIXTURE);
  assert.deepEqual(clean.warnings, []);
});

// ── minSharpeGone (PUT /api/config/activation-min-sharpe) ──────────────────
function fakeRes() {
  return {
    statusCode: null, body: null,
    status(code) { this.statusCode = code; return this; },
    json(body) { this.body = body; return this; },
  };
}

test('minSharpeGone returns 410 with an explanatory body', () => {
  const res = fakeRes();
  minSharpeGone({}, res);
  assert.equal(res.statusCode, 410);
  assert.equal(res.body, MIN_SHARPE_GONE_BODY);
  assert.match(res.body.error, /removed 2026-09-25/);
  assert.match(res.body.error, /bench-relative/);
});

// ── Wiring check: server.js actually registers these handlers ─────────────
// Proves the routes are wired to the extracted, unit-tested functions
// WITHOUT executing server.js (which would require booting Express/DB
// connections -- exactly what this file's docstring says to avoid). Reads
// the source text and asserts both route registrations reference the
// imported names.
test('server.js wires GET/PUT /api/config/activation-min-sharpe to the extracted helpers', () => {
  const src = fs.readFileSync(SERVER_JS, 'utf8');
  assert.match(src, /require\(['"]\.\/activation_preview['"]\)/);
  assert.match(src, /benchCardPayload/, 'benchCardPayload must be imported/used');
  assert.match(src,
    /app\.put\(['"]\/api\/config\/activation-min-sharpe['"],\s*minSharpeGone\)/,
    'PUT route must be wired directly to minSharpeGone');
  assert.match(src,
    /app\.get\(['"]\/api\/config\/activation-min-sharpe['"]/,
    'GET route must still exist');
  // The min-Sharpe slider's own pipeline_config key must never be written
  // again anywhere in server.js (the PUT that used to INSERT it is gone).
  assert.doesNotMatch(src, /INSERT INTO pipeline_config[\s\S]{0,80}strategy_activation_min_sharpe/);
});

// ── benchCardPayload (pure, DB-free) ────────────────────────────────────────
const MARKER_WITH_BENCH = {
  value: JSON.stringify({
    min_trades: 100, activated_cells: 3, deactivated_cells: 7, trigger: 'weekly_cron',
    bench_sharpe: { LOW_VOL: 0.95, TRANSITIONING: 0.44, HIGH_VOL: 0.53, CRISIS: 1.58 },
    bench_run_id: 'r51b5b915', bench_hysteresis: 0.10,
  }),
  updated_at: '2026-09-26T04:00:02.000Z',
};
const MARKER_PRE_TASK1 = {
  // Stamped before Task 1 ever wrote bench_sharpe/bench_hysteresis/bench_run_id.
  value: JSON.stringify({ threshold: 0.5, min_trades: 100, trigger: 'daily_cycle' }),
  updated_at: '2026-08-22T15:00:00.000Z',
};
const TIER2_FALLBACK_ROW = {
  value: JSON.stringify({ LOW_VOL: 0.81, TRANSITIONING: 0.42, HIGH_VOL: 0.49, CRISIS: 1.54 }),
  updated_at: '2026-08-30T09:21:00.000Z',
};

test('benchCardPayload: marker with bench_sharpe -> source last_applied, own hysteresis/run_id', () => {
  const out = benchCardPayload(MARKER_WITH_BENCH, null);
  assert.deepEqual(out.bench, { LOW_VOL: 0.95, TRANSITIONING: 0.44, HIGH_VOL: 0.53, CRISIS: 1.58 });
  assert.equal(out.source, 'last_applied');
  assert.equal(out.hysteresis, 0.10);
  assert.equal(out.bench_run_id, 'r51b5b915');
  assert.equal(out.row_exists, true);
  assert.equal(out.applied_at, MARKER_WITH_BENCH.updated_at);
  // No bench_regime_source on this marker (predates F1-c) -> no per-regime
  // provenance known, no notes guessed at.
  assert.equal(out.regime_source, null);
  assert.deepEqual(out.bench_notes, {});
});

// ── F1-c (fix round 1): per-regime provenance / degraded-regime notes ──────
const MARKER_WITH_DEGRADED_REGIME = {
  value: JSON.stringify({
    min_trades: 100, activated_cells: 1, deactivated_cells: 2, trigger: 'daily_cycle',
    bench_sharpe: { LOW_VOL: 0.95, TRANSITIONING: 0.44, HIGH_VOL: 0.53, CRISIS: 0.50 },
    bench_run_id: 'r51b5b915', bench_hysteresis: 0.10,
    bench_regime_source: { LOW_VOL: 'sleeve', TRANSITIONING: 'sleeve',
                           HIGH_VOL: 'pipeline_config', CRISIS: 'default' },
  }),
  updated_at: '2026-09-26T15:00:00.000Z',
};

test('benchCardPayload: a defaulted regime is marked "DEFAULT 0.50 — WARN", a pipeline_config regime "fallback", sleeve regimes unmarked', () => {
  const out = benchCardPayload(MARKER_WITH_DEGRADED_REGIME, null);
  assert.deepEqual(out.regime_source,
    { LOW_VOL: 'sleeve', TRANSITIONING: 'sleeve', HIGH_VOL: 'pipeline_config', CRISIS: 'default' });
  assert.deepEqual(out.bench_notes, { HIGH_VOL: 'fallback', CRISIS: 'DEFAULT 0.50 — WARN' });
  assert.equal(out.bench_notes.LOW_VOL, undefined);
  assert.equal(out.bench_notes.TRANSITIONING, undefined);
});

test('benchCardPayload: tier-2 fallback source has no per-regime provenance (regime_source null, no notes)', () => {
  // Even though the tier-2 row IS a fully degraded comparator (the marker
  // predates the bench rule entirely), it carries no per-regime
  // bench_regime_source of its own -- that field lives on the MARKER
  // (stamp_last_applied), not the standalone tier-2 pipeline_config row.
  const out = benchCardPayload(MARKER_PRE_TASK1, TIER2_FALLBACK_ROW);
  assert.equal(out.source, 'pipeline_config_fallback');
  assert.equal(out.regime_source, null);
  assert.deepEqual(out.bench_notes, {});
});

test('benchCardPayload: pre-Task-1 marker + tier-2 fallback row -> source pipeline_config_fallback', () => {
  const out = benchCardPayload(MARKER_PRE_TASK1, TIER2_FALLBACK_ROW);
  assert.deepEqual(out.bench, { LOW_VOL: 0.81, TRANSITIONING: 0.42, HIGH_VOL: 0.49, CRISIS: 1.54 });
  assert.equal(out.source, 'pipeline_config_fallback');
  // Marker predates bench_hysteresis -- falls back to the code default.
  assert.equal(out.hysteresis, 0.10);
  assert.equal(out.bench_run_id, null);
  assert.equal(out.row_exists, true);
});

test('benchCardPayload: neither row present -> bench null, source null, row_exists false', () => {
  const out = benchCardPayload(null, null);
  assert.equal(out.bench, null);
  assert.equal(out.source, null);
  assert.equal(out.row_exists, false);
  assert.equal(out.applied_at, null);
  assert.equal(out.hysteresis, 0.10);
});

test('benchCardPayload: malformed marker JSON -> treated as absent, falls through to tier-2', () => {
  const out = benchCardPayload({ value: '{not valid json', updated_at: '2026-09-01T00:00:00Z' }, TIER2_FALLBACK_ROW);
  assert.deepEqual(out.bench, { LOW_VOL: 0.81, TRANSITIONING: 0.42, HIGH_VOL: 0.49, CRISIS: 1.54 });
  assert.equal(out.source, 'pipeline_config_fallback');
  // row_exists reflects the MARKER row's existence (it exists, just
  // unparsable), not whether it yielded usable data.
  assert.equal(out.row_exists, true);
});

test('benchCardPayload: malformed tier-2 fallback JSON -> bench stays null (no throw)', () => {
  const out = benchCardPayload(MARKER_PRE_TASK1, { value: 'not json at all', updated_at: '2026-08-30T00:00:00Z' });
  assert.equal(out.bench, null);
  assert.equal(out.source, null);
});

test('benchCardPayload: caller-supplied defaultBand overrides the module default', () => {
  const out = benchCardPayload(MARKER_PRE_TASK1, null, 0.25);
  assert.equal(out.hysteresis, 0.25);
});

// ── EXCESS slider (spec Amendment 1 §8, Task 4) ─────────────────────────────

// header line with the new append-only excess= token (real assigner
// f-string shape, generated by hand to match main()'s header f-string —
// this file's own convention already hand-writes several HEADER/SUMMARY
// fixtures elsewhere, e.g. the singular-newly-dormant test above).
test('header line with excess= parses threshold/min_trades/strategies AND the new excess field', () => {
  const p = parseActivationDryRun(
    '[activation_assigner] threshold=1.25 min_trades=100 dry_run=True strategies=278 excess=0.3\n'
  );
  assert.equal(p.threshold, 1.25);
  assert.equal(p.min_trades, 100);
  assert.equal(p.excess, 0.3);
});

test('old-shape header (no excess=) still matches; excess falls back to null', () => {
  const p = parseActivationDryRun(
    '[activation_assigner] threshold=0.5 min_trades=20 dry_run=True strategies=149\n'
  );
  assert.equal(p.threshold, 0.5);
  assert.equal(p.min_trades, 20);
  assert.equal(p.excess, null);
  assert.equal(p.thresholds, null);
});

// thresholds: line (generated via `PYTHONPATH=src python3 -c "from backtest
// import activation_assigner as aa; print(aa._fmt_thresholds(...))"`, no DB
// — same convention as the bench:/bench diff: fixtures above).
test('thresholds: line parses the per-regime effective comparator', () => {
  const p = parseActivationDryRun(
    '[activation_assigner] thresholds: LOW_VOL=1.25 TRANSITIONING=0.74 HIGH_VOL=0.83 CRISIS=1.88 (excess=0.3)\n'
  );
  assert.deepEqual(p.thresholds, {
    LOW_VOL: 1.25, TRANSITIONING: 0.74, HIGH_VOL: 0.83, CRISIS: 1.88,
  });
  assert.equal(p.excess, 0.3);   // no header in this snippet -> falls back to the thresholds line
});

test('header excess wins over the thresholds line excess when both are present', () => {
  const p = parseActivationDryRun(
    '[activation_assigner] threshold=1.25 min_trades=100 dry_run=True strategies=278 excess=0.3\n' +
    '[activation_assigner] thresholds: LOW_VOL=1.25 TRANSITIONING=0.74 HIGH_VOL=0.83 CRISIS=1.88 (excess=0.3)\n'
  );
  assert.equal(p.excess, 0.3);
  assert.ok(p.thresholds);
});

test('thresholds: line never matches HEADER/DETAIL/SUMMARY/bench:/bench diff:/WARN', () => {
  const line = '[activation_assigner] thresholds: LOW_VOL=1.25 TRANSITIONING=0.74 HIGH_VOL=0.83 CRISIS=1.88 (excess=0.3)';
  // Spliced into the full authentic FIXTURE -- summary/detail counts must
  // be unaffected (mirrors the equivalent bench: splice test above).
  const withThresholds = FIXTURE.replace(
    '[activation_assigner] activation_assigner summary:',
    line + '\n[activation_assigner] activation_assigner summary:'
  );
  const p = parseActivationDryRun(withThresholds);
  assert.equal(p.evaluated, 4);
  assert.deepEqual(p.thresholds, { LOW_VOL: 1.25, TRANSITIONING: 0.74, HIGH_VOL: 0.83, CRISIS: 1.88 });
});

// ── clampExcessValue ─────────────────────────────────────────────────────
test('clampExcessValue: valid numbers and numeric strings pass through rounded to 0.05', () => {
  assert.equal(clampExcessValue(0.3), 0.3);
  assert.equal(clampExcessValue('0.3'), 0.3);
  assert.equal(clampExcessValue(0.32), 0.3);    // rounds to nearest 0.05
  assert.equal(clampExcessValue(-0.5), -0.5);
  assert.equal(clampExcessValue(0), 0);
});

test('clampExcessValue: clamps out-of-range values to [-1.0, 2.0]', () => {
  assert.equal(clampExcessValue(5), ACTIVATION_EXCESS_MAX);
  assert.equal(clampExcessValue(-5), ACTIVATION_EXCESS_MIN);
});

test('clampExcessValue: rejects non-finite, missing, and wrong-typed values', () => {
  for (const bad of [NaN, Infinity, -Infinity, null, undefined, '', 'abc', true, false, [1], {}]) {
    assert.equal(clampExcessValue(bad), null, JSON.stringify(bad));
  }
});

// ── excessCardPayload ────────────────────────────────────────────────────
test('excessCardPayload: layers excess/thresholds/applied_excess on top of benchCardPayload', () => {
  const excessRow = { value: '0.30', updated_at: '2026-09-27T01:00:00Z' };
  const out = excessCardPayload(MARKER_WITH_BENCH, null, excessRow);
  assert.equal(out.excess, 0.3);
  assert.deepEqual(out.bench, { LOW_VOL: 0.95, TRANSITIONING: 0.44, HIGH_VOL: 0.53, CRISIS: 1.58 });
  assert.deepEqual(out.thresholds, { LOW_VOL: 1.25, TRANSITIONING: 0.74, HIGH_VOL: 0.83, CRISIS: 1.88 });
  // MARKER_WITH_BENCH has no `excess` field (predates Amendment 1) -> 0.
  assert.equal(out.applied_excess, 0);
});

test('excessCardPayload: applied_excess reads the marker’s own excess field when present', () => {
  const markerWithExcess = {
    value: JSON.stringify({
      bench_sharpe: { LOW_VOL: 0.95, TRANSITIONING: 0.44, HIGH_VOL: 0.53, CRISIS: 1.58 },
      bench_run_id: 'r51b5b915', bench_hysteresis: 0.10, excess: 0.3,
    }),
    updated_at: '2026-09-27T04:00:00Z',
  };
  const excessRow = { value: '0.30', updated_at: '2026-09-27T04:05:00Z' };
  const out = excessCardPayload(markerWithExcess, null, excessRow);
  assert.equal(out.excess, 0.3);
  assert.equal(out.applied_excess, 0.3);
});

test('excessCardPayload: missing/malformed excess row defaults to ACTIVATION_EXCESS_DEFAULT', () => {
  const out1 = excessCardPayload(MARKER_WITH_BENCH, null, null);
  assert.equal(out1.excess, ACTIVATION_EXCESS_DEFAULT);
  const out2 = excessCardPayload(MARKER_WITH_BENCH, null, { value: 'not-a-number', updated_at: 'x' });
  assert.equal(out2.excess, ACTIVATION_EXCESS_DEFAULT);
});

test('excessCardPayload: no bench vector -> thresholds are all null, not NaN', () => {
  const out = excessCardPayload(null, null, { value: '0.5', updated_at: 'x' });
  assert.equal(out.bench, null);
  assert.deepEqual(out.thresholds, { LOW_VOL: null, TRANSITIONING: null, HIGH_VOL: null, CRISIS: null });
});

// ── Wiring check: server.js registers the new routes on the extracted
// helpers, without executing server.js (same rationale as the min-sharpe
// wiring check above) ───────────────────────────────────────────────────
test('server.js wires GET/PUT /api/config/activation-excess-sharpe to clampExcessValue/excessCardPayload, and dry-run to clampExcessValue', () => {
  const src = fs.readFileSync(SERVER_JS, 'utf8');
  assert.match(src, /clampExcessValue/, 'clampExcessValue must be imported/used');
  assert.match(src, /excessCardPayload/, 'excessCardPayload must be imported/used');
  assert.match(src,
    /app\.get\(['"]\/api\/config\/activation-excess-sharpe['"]/,
    'GET route must exist');
  assert.match(src,
    /app\.put\(['"]\/api\/config\/activation-excess-sharpe['"]/,
    'PUT route must exist');
  // The old min-Sharpe PUT path must still be distinct and still 410.
  assert.match(src,
    /app\.put\(['"]\/api\/config\/activation-min-sharpe['"],\s*minSharpeGone\)/,
    'old min-Sharpe PUT must remain wired to minSharpeGone (410)');
  // The dry-run route must validate an incoming excess with the SAME
  // clamp function the PUT route uses -- not a second, divergent check.
  const dryRunStart = src.indexOf("app.post('/api/activation/dry-run'");
  assert.ok(dryRunStart >= 0, 'dry-run route not found');
  const dryRunSlice = src.slice(dryRunStart, dryRunStart + 2000);
  assert.match(dryRunSlice, /clampExcessValue\(req\.body\.excess\)/);
});
