// tests/test_activation_slider_api.js
// Unit tests for activation_preview.parseActivationDryRun — the parser
// behind POST /api/activation/dry-run (Strategy Activation slider preview).
// Pure, no DB / no server boot (mirrors tests/test_blend_scope.js).
//
// The FIXTURE below is AUTHENTIC assigner output: generated by driving the
// real src/backtest/activation_assigner.py _log/_fmt_diff helpers plus
// main()'s verbatim header/summary f-strings over synthetic results
// (2026-07-11) — not hand-typed. If the assigner's print format changes,
// regenerate rather than editing lines in place.
//
// Run: node tests/test_activation_slider_api.js
const assert = require('assert');
const { parseActivationDryRun, CANONICAL_REGIMES } =
  require('../src/channels/api/activation_preview');

const FIXTURE = `[activation_assigner] threshold=1.85 min_trades=20 dry_run=True strategies=6
[activation_assigner]   ERROR S_zeta_broken: relation 'strategy_backtest_regimes' scan failed
[activation_assigner]   S_alpha_momo: LOW_VOL: True->False (deactivated), TRANSITIONING: None->False (initialized), HIGH_VOL: False->False, CRISIS: True->False (deactivated)
[activation_assigner]   S_beta_meanrev: LOW_VOL: True->True, TRANSITIONING: False->False, HIGH_VOL: False->True (activated), CRISIS: None->False (initialized)
[activation_assigner]   S_gamma_carry: LOW_VOL: False->False, TRANSITIONING: False->False, HIGH_VOL: True->True, CRISIS: True->True
[activation_assigner]   S_delta_pairs: LOW_VOL: None->False (initialized), TRANSITIONING: True->False (deactivated), HIGH_VOL: None->False (initialized), CRISIS: None->False (initialized)
[activation_assigner]   SKIP  S_eps_nodata: no primary_window backtest with regime rows
[activation_assigner] activation_assigner summary: 4 strategies evaluated, 1 skipped (no corrected backtest), 1 cell(s) activated, 3 cell(s) deactivated, 2 newly-dormant strategies (S_alpha_momo, S_delta_pairs), threshold=1.85, min_trades=20, dry_run=True, errors=1
`;

// 1. Full authentic transcript — summary-backed fields + per-regime counts
{
  const p = parseActivationDryRun(FIXTURE);
  assert.strictEqual(p.summary_found, true);
  assert.strictEqual(p.threshold, 1.85);
  assert.strictEqual(p.min_trades, 20);
  assert.strictEqual(p.evaluated, 4);
  assert.strictEqual(p.skipped, 1);
  assert.strictEqual(p.errors, 1);
  assert.deepStrictEqual(p.cells, { activated: 1, deactivated: 3 });
  assert.deepStrictEqual(p.newly_dormant, ['S_alpha_momo', 'S_delta_pairs']);
  assert.strictEqual(p.newly_dormant_count, 2);
  assert.deepStrictEqual(p.warnings, [], 'authentic transcript must cross-check clean');

  // Per-regime: eligible_now = prior True count (DB reality),
  // eligible_preview = new True count (hypothetical).
  assert.deepStrictEqual(p.per_regime.LOW_VOL,
    { eligible_now: 2, eligible_preview: 1, dormant_preview: 3,
      activated: 0, deactivated: 1, initialized: 1, unchanged: 2 });
  assert.deepStrictEqual(p.per_regime.HIGH_VOL,
    { eligible_now: 1, eligible_preview: 2, dormant_preview: 2,
      activated: 1, deactivated: 0, initialized: 1, unchanged: 2 });
  assert.deepStrictEqual(p.per_regime.CRISIS,
    { eligible_now: 2, eligible_preview: 1, dormant_preview: 3,
      activated: 0, deactivated: 1, initialized: 2, unchanged: 1 });

  // changed_strategies excludes the fully-unchanged S_gamma_carry.
  assert.deepStrictEqual(p.changed_strategies.map(s => s.strategy_id),
    ['S_alpha_momo', 'S_beta_meanrev', 'S_delta_pairs']);
  const alpha = p.changed_strategies[0];
  assert.strictEqual(alpha.newly_dormant, true);
  assert.deepStrictEqual(alpha.cells.TRANSITIONING,
    { before: null, after: false, action: 'initialized' });   // None → null
  assert.deepStrictEqual(alpha.cells.LOW_VOL,
    { before: true, after: false, action: 'deactivated' });
  assert.strictEqual(p.changed_strategies_truncated, false);
  assert.ok(p.summary_line.startsWith('[activation_assigner] activation_assigner summary:'));
}

// 2. Singular newly-dormant grammar ("1 newly-dormant strategy (S_x)")
{
  const p = parseActivationDryRun(
    '[activation_assigner] threshold=0.5 min_trades=20 dry_run=True strategies=1\n' +
    '[activation_assigner]   S_x: LOW_VOL: True->False (deactivated), TRANSITIONING: False->False, HIGH_VOL: False->False, CRISIS: False->False\n' +
    '[activation_assigner] activation_assigner summary: 1 strategies evaluated, 0 skipped (no corrected backtest), 0 cell(s) activated, 1 cell(s) deactivated, 1 newly-dormant strategy (S_x), threshold=0.5, min_trades=20, dry_run=True, errors=0\n'
  );
  assert.strictEqual(p.summary_found, true);
  assert.strictEqual(p.newly_dormant_count, 1);
  assert.deepStrictEqual(p.newly_dormant, ['S_x']);
  assert.deepStrictEqual(p.warnings, []);
}

// 3. Zero newly-dormant — the parenthesised list is omitted entirely
{
  const p = parseActivationDryRun(
    '[activation_assigner] threshold=0.5 min_trades=20 dry_run=True strategies=1\n' +
    '[activation_assigner]   S_y: LOW_VOL: False->True (activated), TRANSITIONING: False->False, HIGH_VOL: False->False, CRISIS: False->False\n' +
    '[activation_assigner] activation_assigner summary: 1 strategies evaluated, 0 skipped (no corrected backtest), 1 cell(s) activated, 0 cell(s) deactivated, 0 newly-dormant strategies, threshold=0.5, min_trades=20, dry_run=True, errors=0\n'
  );
  assert.strictEqual(p.summary_found, true);
  assert.strictEqual(p.newly_dormant_count, 0);
  assert.deepStrictEqual(p.newly_dormant, []);
  assert.deepStrictEqual(p.cells, { activated: 1, deactivated: 0 });
  assert.deepStrictEqual(p.warnings, []);
}

// 4. Truncated output (no summary line — e.g. killed mid-run): fall back to
//    per-line counts and surface a warning; never throw.
{
  const p = parseActivationDryRun(
    '[activation_assigner] threshold=0.5 min_trades=20 dry_run=True strategies=3\n' +
    '[activation_assigner]   S_a: LOW_VOL: True->False (deactivated), TRANSITIONING: False->False, HIGH_VOL: False->False, CRISIS: False->False\n' +
    '[activation_assigner]   SKIP  S_b: no primary_window backtest with regime rows\n'
  );
  assert.strictEqual(p.summary_found, false);
  assert.strictEqual(p.threshold, 0.5, 'falls back to header threshold');
  assert.strictEqual(p.min_trades, 20);
  assert.strictEqual(p.evaluated, 1, 'falls back to detail-line count');
  assert.strictEqual(p.skipped, 1);
  assert.deepStrictEqual(p.cells, { activated: 0, deactivated: 1 });
  assert.deepStrictEqual(p.newly_dormant, ['S_a']);
  assert.strictEqual(p.warnings.length, 1);
  assert.ok(/summary line not found/.test(p.warnings[0]));
}

// 5. Garbage / empty input: structured zeros, no throw
{
  for (const junk of ['', null, undefined, 'POSTGRES_URI not set\nTraceback (most recent call last):\n  boom']) {
    const p = parseActivationDryRun(junk);
    assert.strictEqual(p.summary_found, false);
    assert.strictEqual(p.evaluated, 0);
    assert.deepStrictEqual(p.newly_dormant, []);
    for (const r of CANONICAL_REGIMES) {
      assert.strictEqual(p.per_regime[r].eligible_now, 0);
    }
  }
}

// 6. Cross-check discrepancy (summary disagrees with detail lines — format
//    drift guard): warnings must surface it, summary wins for the headline.
{
  const p = parseActivationDryRun(
    '[activation_assigner] threshold=0.5 min_trades=20 dry_run=True strategies=1\n' +
    '[activation_assigner]   S_a: LOW_VOL: True->True, TRANSITIONING: False->False, HIGH_VOL: False->False, CRISIS: False->False\n' +
    '[activation_assigner] activation_assigner summary: 1 strategies evaluated, 0 skipped (no corrected backtest), 4 cell(s) activated, 4 cell(s) deactivated, 1 newly-dormant strategy (S_ghost), threshold=0.5, min_trades=20, dry_run=True, errors=0\n'
  );
  assert.strictEqual(p.summary_found, true);
  assert.ok(p.warnings.some(w => /newly-dormant mismatch/.test(w)));
  assert.ok(p.warnings.some(w => /cell-count mismatch/.test(w)));
  assert.deepStrictEqual(p.newly_dormant, ['S_ghost'], 'summary list preferred when present');
}

console.log('test_activation_slider_api: all assertions passed');
