'use strict';

/**
 * Alpaca tool-module template — generates workspace/tools/alpaca.py.
 *
 * READ-ONLY wrapper around the Alpaca CLI (github.com/alpacahq/cli). The
 * tool-guide names Alpaca P1 for prices / options chain / news / screener /
 * corporate actions / broker state, but until 2026-08-22 the alpaca provider
 * had no template and registry.js emitted the generic HTTP stub (no
 * functions). Sub-agents writing PTC Python had no sanctioned path to the P1
 * source.
 *
 * Deliberately NOT exposed: order submit / cancel / replace / position close /
 * option exercise / locate / raw `alpaca api`. Execution stays in
 * src/execution/alpaca_executor.py behind the sized-handoff + HITL gates.
 *
 * CLI contract encoded here (see docs/reference/alpaca-cli-integration.md):
 *   - JSON is the default output; there is NO --json flag. Every call passes
 *     --quiet (no hints on stderr) and --timeout.
 *   - exit 0 ok / 1 API error / 2 auth error. Errors are a JSON document on
 *     stderr — parsed as a whole (v0.0.10+ pretty-prints it over many lines).
 *   - `order list` defaults to 50 rows, caps --limit at 500, and hides OCO
 *     stop legs unless --nested. Reads keyset-paginate with --after-order-id.
 *   - Data endpoints page via next_page_token; multi-symbol endpoints are
 *     used with symbols chunked (URL length), bars --limit 10000 (API max).
 *   - Credentials come from ALPACA_API_KEY/ALPACA_SECRET_KEY in the process
 *     env (inherited). ALPACA_LIVE_TRADE=false keeps the paper account.
 */

const ALPACA_BIN_DEFAULT = '/root/go/bin/alpaca';

function generatePython(server) {
  return `# Auto-generated by registry.js from src/agent/tools/mcp/alpaca.js — do not edit manually
# ${server.description}
#
# READ-ONLY wrapper over the Alpaca CLI (/root/go/bin/alpaca). No function here
# submits, replaces, cancels or closes anything — execution lives in
# src/execution/alpaca_executor.py behind the sized-handoff + HITL gates.
#
# Usage (PTC):
#     from tools.alpaca import get_bars, get_snapshots, get_news, get_option_chain
#     bars = get_bars(["AAPL", "MSFT"], start="2026-01-01", timeframe="1Day")
#     bars["AAPL"][-1]["c"]
#
# Errors: AlpacaCLIError(rc, status, code, error, hint). AlpacaAuthError (rc=2)
# means credentials are wrong — do NOT retry, report it.
import os, json, subprocess
from _rate_limiter import _acquire_token, _cycle_cache_get, _cycle_cache_set

ALPACA_BIN = os.environ.get("ALPACA_CLI_BIN", "${ALPACA_BIN_DEFAULT}")
_PROVIDER = "alpaca"
_DEFAULT_TIMEOUT = 30        # seconds; passed to the CLI as --timeout and enforced +5s on the subprocess
_SYMBOL_CHUNK = 200          # symbols per multi-* request (URL length headroom)
_ORDERS_PAGE = 500           # 'order list' hard cap
_ORDERS_MAX_PAGES = 40
_NEWS_MAX_LIMIT = 50         # /v1beta1/news cap
_BARS_MAX_LIMIT = 10000      # /v2/stocks/bars cap
_OPTION_MAX_LIMIT = 1000     # options snapshots cap
_CA_MAX_LIMIT = 1000         # corporate-actions cap


class AlpacaCLIError(RuntimeError):
    """Non-zero exit from the CLI. Fields mirror the CLI's stderr JSON."""
    def __init__(self, rc, status=None, code=None, error="", hint="", args=()):
        self.rc, self.status, self.code, self.error, self.hint, self.args_ = rc, status, code, error, hint, tuple(args)
        msg = f"alpaca {' '.join(self.args_)} -> rc={rc}"
        if status is not None:
            msg += f" status={status}"
        if code is not None:
            msg += f" code={code}"
        if error:
            msg += f": {error}"
        if hint:
            msg += f" (hint: {hint})"
        super().__init__(msg)


class AlpacaAuthError(AlpacaCLIError):
    """rc=2 — credentials missing/invalid. Never retry; surface to the operator."""


def _parse_stderr(text):
    text = (text or "").strip()
    if not text:
        return {}
    try:
        obj = json.loads(text)          # whole document — may be pretty-printed over many lines
        return obj if isinstance(obj, dict) else {"error": text[:500]}
    except ValueError:
        return {"error": text[:500]}


def _run(args, timeout=_DEFAULT_TIMEOUT, cache=False):
    """Run one read-only CLI command and return its parsed JSON stdout.

    cache=True routes through the per-cycle Redis cache (data reads only —
    broker state must always be fresh)."""
    args = [str(a) for a in args]
    cmd = [ALPACA_BIN, *args, "--quiet", "--timeout", str(int(timeout))]
    if cache:
        hit = _cycle_cache_get("alpaca:cli", cmd)
        if hit is not None:
            return hit
    _acquire_token(_PROVIDER)
    try:
        p = subprocess.run(cmd, capture_output=True, text=True, timeout=int(timeout) + 5)
    except FileNotFoundError:
        raise AlpacaCLIError(127, error=f"alpaca CLI not found at {ALPACA_BIN}", args=args)
    except subprocess.TimeoutExpired:
        raise AlpacaCLIError(124, error=f"alpaca CLI timed out after {int(timeout) + 5}s", args=args)
    if p.returncode != 0:
        ej = _parse_stderr(p.stderr)
        cls = AlpacaAuthError if p.returncode == 2 else AlpacaCLIError
        raise cls(p.returncode, status=ej.get("status"), code=ej.get("code"),
                  error=ej.get("error") or "", hint=ej.get("hint") or "", args=args)
    out = p.stdout.strip()
    data = json.loads(out) if out else None
    if cache:
        _cycle_cache_set("alpaca:cli", cmd, data)
    return data


def _symbols(symbols, crypto=False):
    """Normalise a list or comma-string of symbols. Crypto uses BTC/USD form."""
    if isinstance(symbols, str):
        symbols = symbols.split(",")
    out = []
    for s in symbols:
        s = str(s).strip().upper()
        if not s:
            continue
        if crypto:
            s = s.replace("-", "/")
            if "/" not in s and s.endswith("USD"):
                s = s[:-3] + "/USD"
        out.append(s)
    return out


def _chunks(seq, n=_SYMBOL_CHUNK):
    for i in range(0, len(seq), n):
        yield seq[i:i + n]


def _opt(args, flag, value):
    """Append --flag value when value is not None/empty."""
    if value is None or value == "" or value == []:
        return args
    if isinstance(value, (list, tuple)):
        value = ",".join(str(v) for v in value)
    args.extend([flag, str(value)])
    return args


def _paginate(args, key, timeout=_DEFAULT_TIMEOUT, max_pages=20, cache=True):
    """Follow next_page_token. Merges dict-of-lists (bars/snapshots) or lists."""
    merged, token, pages = None, None, 0
    while True:
        page_args = list(args) + (["--page-token", token] if token else [])
        page = _run(page_args, timeout=timeout, cache=cache)
        chunk = page.get(key) if isinstance(page, dict) else page
        if isinstance(chunk, dict):
            merged = merged if isinstance(merged, dict) else {}
            for sym, rows in chunk.items():
                if isinstance(rows, list):
                    merged.setdefault(sym, []).extend(rows)
                else:
                    merged[sym] = rows
        elif isinstance(chunk, list):
            merged = (merged if isinstance(merged, list) else []) + chunk
        pages += 1
        token = page.get("next_page_token") if isinstance(page, dict) else None
        if not token or pages >= max_pages:
            break
    if merged is None:
        merged = {} if key in ("bars", "snapshots", "trades", "quotes") else []
    return merged


# ── Broker state (never cached) ───────────────────────────────────────────

def get_account(timeout=_DEFAULT_TIMEOUT):
    """GET /v2/account — equity, cash, buying_power, status, ... (paper unless ALPACA_LIVE_TRADE=true)."""
    return _run(["account", "get"], timeout=timeout)


def get_positions(timeout=_DEFAULT_TIMEOUT):
    """All open positions (list). qty_available reflects shares reserved by resting OCO legs."""
    return _run(["position", "list"], timeout=timeout) or []


def get_open_orders(symbols=None, status="open", nested=True, timeout=45):
    """ALL orders of 'status' (default open), keyset-paginated past the 500-row cap.

    nested=True rolls OCO/bracket legs under order['legs'] — without it a
    protective stop is INVISIBLE (the top-level row is the take-profit with
    stop_price=null). Exclude status='pending_cancel' rows downstream; 'held'
    is the normal resting state of an OCO stop leg."""
    base = ["order", "list", "--status", status, "--limit", str(_ORDERS_PAGE), "--direction", "asc"]
    if nested:
        base.append("--nested")
    _opt(base, "--symbols", _symbols(symbols) if symbols else None)
    out, cursor = [], None
    for _ in range(_ORDERS_MAX_PAGES):
        args = list(base) + (["--after-order-id", cursor] if cursor else [])
        page = _run(args, timeout=timeout) or []
        out.extend(page)
        if len(page) < _ORDERS_PAGE:
            break
        cursor = page[-1].get("id")
        if not cursor:
            break
    return out


def get_clock(timeout=_DEFAULT_TIMEOUT):
    """{is_open, next_open, next_close, timestamp} — authoritative market-hours source."""
    return _run(["clock"], timeout=timeout)


def get_asset(symbol, timeout=_DEFAULT_TIMEOUT):
    """Asset record: tradable, shortable, easy_to_borrow, fractionable, status."""
    return _run(["asset", "get", "--symbol-or-asset-id", str(symbol).strip().upper()], timeout=timeout)


# ── Calendar / reference (cached per cycle) ───────────────────────────────

def get_calendar(start, end, timeout=_DEFAULT_TIMEOUT):
    """Trading calendar rows [{date, open, close, session_open, session_close}] for start..end inclusive."""
    args = ["calendar"]
    _opt(args, "--start", start)
    _opt(args, "--end", end)
    return _run(args, timeout=timeout, cache=True) or []


# ── Market data (cached per cycle) ────────────────────────────────────────

def get_bars(symbols, start, end=None, timeframe="1Day", adjustment="raw", feed="sip",
             limit=_BARS_MAX_LIMIT, max_pages=20, timeout=60):
    """Historical bars for many symbols in one call path: {SYMBOL: [{t,o,h,l,c,v,n,vw}, ...]}.

    Uses 'data multi-bars' (chunked ≤200 symbols, --limit 10000, follows
    next_page_token) instead of one process per ticker. timeframe: 1Min..59Min,
    1Hour..23Hour, 1Day, 1Week, 1Month. adjustment: raw|split|dividend|all."""
    out = {}
    for chunk in _chunks(_symbols(symbols)):
        args = ["data", "multi-bars", "--symbols", ",".join(chunk), "--timeframe", timeframe,
                "--adjustment", adjustment, "--feed", feed, "--limit", str(min(int(limit), _BARS_MAX_LIMIT)),
                "--sort", "asc"]
        _opt(args, "--start", start)
        _opt(args, "--end", end)
        out.update(_paginate(args, "bars", timeout=timeout, max_pages=max_pages))
    return out


def get_snapshots(symbols, feed=None, timeout=_DEFAULT_TIMEOUT):
    """Latest trade/quote/minute bar/daily bar/prev daily bar per symbol: {SYMBOL: {...}}."""
    out = {}
    for chunk in _chunks(_symbols(symbols)):
        args = ["data", "multi-snapshots", "--symbols", ",".join(chunk)]
        _opt(args, "--feed", feed)
        out.update(_run(args, timeout=timeout, cache=True) or {})
    return out


def get_latest_trades(symbols, feed=None, timeout=_DEFAULT_TIMEOUT):
    """Latest trade per symbol: {SYMBOL: {t, p, s, x, ...}}."""
    out = {}
    for chunk in _chunks(_symbols(symbols)):
        args = ["data", "latest-trades", "--symbols", ",".join(chunk)]
        _opt(args, "--feed", feed)
        page = _run(args, timeout=timeout, cache=True) or {}
        out.update(page.get("trades", page) if isinstance(page, dict) else {})
    return out


def get_crypto_bars(symbols, start, end=None, timeframe="1Day", limit=_BARS_MAX_LIMIT, max_pages=20, timeout=60):
    """Crypto bars {BTC/USD: [...]} — symbols accepted as BTC-USD, BTCUSD or BTC/USD."""
    out = {}
    for chunk in _chunks(_symbols(symbols, crypto=True)):
        args = ["data", "crypto", "bars", "--symbols", ",".join(chunk), "--timeframe", timeframe,
                "--limit", str(min(int(limit), _BARS_MAX_LIMIT)), "--sort", "asc"]
        _opt(args, "--start", start)
        _opt(args, "--end", end)
        out.update(_paginate(args, "bars", timeout=timeout, max_pages=max_pages))
    return out


def get_crypto_snapshots(symbols, timeout=_DEFAULT_TIMEOUT):
    """Crypto snapshots {BTC/USD: {latestTrade, latestQuote, ...}}."""
    out = {}
    for chunk in _chunks(_symbols(symbols, crypto=True)):
        page = _run(["data", "crypto", "snapshots", "--symbols", ",".join(chunk)], timeout=timeout, cache=True) or {}
        out.update(page.get("snapshots", page) if isinstance(page, dict) else {})
    return out


def get_news(symbols=None, start=None, end=None, limit=_NEWS_MAX_LIMIT, max_pages=2,
             include_content=False, timeout=_DEFAULT_TIMEOUT):
    """News articles (newest first). API caps limit at 50/page; max_pages bounds the total."""
    args = ["data", "news", "--limit", str(max(1, min(int(limit), _NEWS_MAX_LIMIT))), "--sort", "desc",
            "--exclude-contentless"]
    if include_content:
        args.append("--include-content")
    _opt(args, "--symbols", _symbols(symbols) if symbols else None)
    _opt(args, "--start", start)
    _opt(args, "--end", end)
    return _paginate(args, "news", timeout=timeout, max_pages=max_pages)


def get_corporate_actions(symbols=None, start=None, end=None, types=None, max_pages=10, timeout=_DEFAULT_TIMEOUT):
    """Corporate actions grouped by type: {forward_splits: [...], reverse_splits: [...], cash_dividends: [...], ...}.

    types: list of forward_split|reverse_split|unit_split|cash_dividend|stock_dividend|
    spin_off|cash_merger|stock_merger|stock_and_cash_merger|redemption|name_change|
    worthless_removal|rights_distribution."""
    args = ["data", "corporate-actions", "--limit", str(_CA_MAX_LIMIT), "--sort", "asc"]
    _opt(args, "--symbols", _symbols(symbols) if symbols else None)
    _opt(args, "--start", start)
    _opt(args, "--end", end)
    _opt(args, "--types", types)
    merged = {}
    token, pages = None, 0
    while True:
        page_args = list(args) + (["--page-token", token] if token else [])
        page = _run(page_args, timeout=timeout, cache=True) or {}
        for kind, rows in (page.get("corporate_actions") or {}).items():
            merged.setdefault(kind, []).extend(rows or [])
        pages += 1
        token = page.get("next_page_token")
        if not token or pages >= max_pages:
            break
    return merged


def get_option_chain(underlying, expiration_gte=None, expiration_lte=None, expiration=None,
                     strike_gte=None, strike_lte=None, type=None, feed="opra",
                     limit=_OPTION_MAX_LIMIT, max_pages=10, timeout=60):
    """Option chain snapshots {OCC_SYMBOL: {latestQuote, latestTrade, impliedVolatility, greeks}}.

    Filter aggressively (expiration window, strike band, type=call|put) — a full
    chain on a liquid name is thousands of contracts. Contracts with
    greeks={0,...} exist (see _greeks_filter.py)."""
    args = ["data", "option", "chain", "--underlying-symbol", str(underlying).strip().upper(),
            "--feed", feed, "--limit", str(min(int(limit), _OPTION_MAX_LIMIT))]
    _opt(args, "--expiration-date", expiration)
    _opt(args, "--expiration-date-gte", expiration_gte)
    _opt(args, "--expiration-date-lte", expiration_lte)
    _opt(args, "--strike-price-gte", strike_gte)
    _opt(args, "--strike-price-lte", strike_lte)
    _opt(args, "--type", type)
    return _paginate(args, "snapshots", timeout=timeout, max_pages=max_pages)


def get_option_contracts(underlying_symbols, expiration_gte=None, expiration_lte=None, type=None,
                         status="active", strike_gte=None, strike_lte=None, limit=10000, max_pages=10,
                         timeout=60):
    """Tradable option contract definitions (trading API): [{symbol, strike_price, expiration_date, type, ...}]."""
    args = ["option", "contracts", "--underlying-symbols", ",".join(_symbols(underlying_symbols)),
            "--limit", str(int(limit))]
    _opt(args, "--status", status)
    _opt(args, "--expiration-date-gte", expiration_gte)
    _opt(args, "--expiration-date-lte", expiration_lte)
    _opt(args, "--strike-price-gte", strike_gte)
    _opt(args, "--strike-price-lte", strike_lte)
    _opt(args, "--type", type)
    return _paginate(args, "option_contracts", timeout=timeout, max_pages=max_pages)


def get_screener_movers(market_type="stocks", top=10, timeout=_DEFAULT_TIMEOUT):
    """Top gainers/losers by % change: {gainers: [...], losers: [...], market_type, last_updated}."""
    return _run(["data", "screener", "movers", "--market-type", market_type, "--top", str(int(top))],
                timeout=timeout, cache=True)


def get_screener_most_actives(by="volume", top=10, timeout=_DEFAULT_TIMEOUT):
    """Most active stocks by volume|trades: {most_actives: [{symbol, volume, trade_count}], last_updated}."""
    return _run(["data", "screener", "most-actives", "--by", by, "--top", str(int(top))],
                timeout=timeout, cache=True)


__all__ = [
    "AlpacaCLIError", "AlpacaAuthError",
    "get_account", "get_positions", "get_open_orders", "get_clock", "get_asset", "get_calendar",
    "get_bars", "get_snapshots", "get_latest_trades", "get_crypto_bars", "get_crypto_snapshots",
    "get_news", "get_corporate_actions", "get_option_chain", "get_option_contracts",
    "get_screener_movers", "get_screener_most_actives",
]
`;
}

module.exports = { generatePython, ALPACA_BIN_DEFAULT };
