"""
Hardcoded SP500 membership projected to history as the in_sp500 proxy.
Sourced from src/pipeline/universe.js — kept in sync manually until a
historical-membership data source is added (future enhancement).
"""
SP500_SET = frozenset({
    "AAPL", "ABBV", "ABNB", "ABT", "ADBE", "ADI", "AEE", "AEP", "AFL", "AGCO",
    "AIG", "AIR", "AKAM", "ALB", "ALGN", "ALL", "AMAT", "AMCR", "AMD", "AME",
    "AMGN", "AMH", "AMT", "AMZN", "AN", "AON", "AOS", "APA", "APD", "APTV",
    "ARE", "AVB", "AVGO", "AVY", "AXP", "AXTA", "AZO", "BA", "BAC", "BAX",
    "BBY", "BIIB", "BK", "BKNG", "BKR", "BLK", "BLL", "BMY", "BOH", "BRK-B",
    "BRO", "BSX", "BWA", "BXP", "C", "CAG", "CARR", "CAT", "CB", "CBOE",
    "CCI", "CCK", "CCL", "CDNS", "CDW", "CE", "CF", "CFG", "CHD", "CHRW",
    "CHTR", "CI", "CINF", "CL", "CLX", "CMA", "CMCSA", "CME", "CMG", "CMS",
    "CNC", "CNP", "COF", "COO", "COP", "COST", "COTY", "CPB", "CPRI", "CPT",
    "CRL", "CRM", "CSCO", "CSX", "CTAS", "CTRA", "CTVA", "CUBE", "CVS", "CVX",
    "CZR", "D", "DD", "DE", "DECK", "DGX", "DHI", "DHR", "DIA", "DIS",
    "DLR", "DOV", "DRI", "DUK", "DVA", "DVN", "DXC", "DXCM", "EA", "EBAY",
    "ECL", "EL", "ELV", "EMN", "EMR", "ENPH", "EOG", "EPAM", "EPD", "EQIX",
    "EQR", "EQT", "ES", "ET", "ETN", "ETR", "ETSY", "EVRG", "EW", "EWBC",
    "EXAS", "EXC", "EXPD", "EXPE", "EXR", "F", "FANG", "FAST", "FCX", "FDS",
    "FDX", "FE", "FFIV", "FG", "FHN", "FITB", "FOX", "FOXA", "FR", "FSLR",
    "FTNT", "FW", "GD", "GDDY", "GE", "GEHC", "GEN", "GILD", "GIS", "GL",
    "GLW", "GM", "GOOG", "GOOGL", "GPC", "GS", "GVA", "GWW", "HAL", "HAS",
    "HBAN", "HD", "HII", "HLT", "HOLX", "HON", "HPE", "HPQ", "HRL", "HSIC",
    "HSY", "HUBB", "HUM", "IBM", "ICE", "IDXX", "IEX", "IFF", "INCY", "INTU",
    "INVH", "IP", "IPG", "IQV", "IR", "ISRG", "ITW", "IWM", "J", "JBHT",
    "JCI", "JNJ", "JPM", "KEY", "KEYS", "KHC", "KIM", "KLAC", "KMB", "KMI",
    "KMX", "KO", "LDOS", "LEN", "LH", "LII", "LIN", "LKQ", "LLY", "LMT",
    "LNC", "LNG", "LNT", "LOW", "LRCX", "LYV", "MA", "MAA", "MAR", "MCD",
    "MCHP", "MCO", "MDLZ", "MDT", "MET", "META", "MGM", "MKC", "MLM", "MMC",
    "MMM", "MO", "MOH", "MOS", "MPC", "MPWR", "MRK", "MRNA", "MS", "MSC",
    "MSCI", "MSFT", "MTB", "MTCH", "MTD", "MTZ", "MU", "NCLH", "NDAQ", "NEE",
    "NEM", "NFLX", "NI", "NKE", "NNN", "NOC", "NOW", "NRG", "NSC", "NTAP",
    "NTRA", "NTRS", "NUE", "NVDA", "NVR", "NWS", "NWSA", "O", "OKE", "OMC",
    "ORCL", "ORLY", "OTIS", "OXY", "PANW", "PCAR", "PEP", "PFE", "PG", "PH",
    "PHM", "PKG", "PKI", "PLD", "PM", "PNC", "PNW", "PODD", "POOL", "PPG",
    "PRU", "PSA", "PSX", "PTC", "PVH", "PWR", "QCOM", "QQQ", "RCL", "REGN",
    "REXR", "RF", "RJF", "RL", "RMD", "ROK", "ROP", "ROST", "RPM", "RSG",
    "RTX", "SAIC", "SBUX", "SCHW", "SEE", "SHW", "SLB", "SLG", "SNPS", "SO",
    "SON", "SPB", "SPCX", "SPG", "SPGI", "SPR", "SPY", "SRE", "STE", "STT", "STX",
    "SWKS", "SYK", "SYY", "T", "TDG", "TECH", "TEL", "TER", "TFC", "TJX",
    "TMO", "TMUS", "TOL", "TPR", "TRNO", "TRV", "TSLA", "TSN", "TT", "TTWO",
    "TXN", "UAA", "UNH", "UNM", "UNP", "UPS", "URI", "USB", "V", "VFC",
    "VLO", "VMC", "VRSN", "VRT", "VRTX", "VTR", "VZ", "WAL", "WBD", "WDC",
    "WEC", "WELL", "WFC", "WM", "WMB", "WMT", "WTW", "XEL", "XOM", "XYL",
    "YUM", "ZBRA", "ZG", "ZION", "ZTS",
})
