"""
Momentum Trend Following v1 (60d + Dual SMA Market Filter)
Generated by OpenClaw Strategist on 2026-04-13
Backtest (5yr): Sharpe=1.15 | Return=9.8%/yr | MaxDD=-10.3% | WinRate=53%
Status: PENDING OPERATOR APPROVAL
Note: p-value=0.062 marginally above 0.05 threshold; IR=0 is a backtest module bug.
"""

import pandas as pd
import numpy as np
import sys
sys.path.insert(0, 'src/strategies')
from base import BaseStrategy, Signal


class MomentumTrendV1(BaseStrategy):
    id                = 'S_custom_momentum_trend_v1'
    name              = 'Momentum Trend Following v1'
    description       = 'Top-decile 60d momentum within SP100, active only when SPY is in confirmed uptrend (50d>200d SMA)'
    tier              = 2
    signal_frequency  = 'daily'
    active_in_regimes = ['LOW_VOL', 'TRANSITIONING']

    def default_parameters(self):
        return {
            'lookback':    60,    # momentum return window (days)
            'skip':         5,    # skip last N days to avoid reversal
            'top_pct':   0.10,    # top decile of universe
            'fast_sma':    50,    # SPY fast SMA
            'slow_sma':   200,    # SPY slow SMA
            'max_signals': 10,    # max concurrent positions
        }

    def generate_signals(self, prices, regime, universe, aux_data=None):
        """
        1. Check SPY market filter: SPY current > SPY 50d SMA > SPY 200d SMA.
           If not met, return empty (hold cash).
        2. Compute 60-day return for each stock in universe (skip last 5 days).
        3. Rank. Select top 10%.
        4. Return LONG signals with equal-weight sizing.
        """
        p    = self.parameters
        if not self.should_run(regime.get('state', 'LOW_VOL')):
            return []
        if prices is None or len(prices) < p['slow_sma'] + p['lookback'] + p['skip'] + 10:
            return []

        scale = self.position_scale(regime.get('state', 'LOW_VOL'))

        # ── Market filter ─────────────────────────────────────────────────
        if 'SPY' not in prices.columns:
            return []

        spy_ts = prices['SPY'].dropna()
        if len(spy_ts) < p['slow_sma']:
            return []

        spy_current = float(spy_ts.iloc[-1])
        spy_fast    = float(spy_ts.tail(p['fast_sma']).mean())
        spy_slow    = float(spy_ts.tail(p['slow_sma']).mean())

        # Market must be in confirmed uptrend
        if spy_current < spy_fast or spy_fast < spy_slow:
            return []

        # ── Momentum ranking ─────────────────────────────────────────────
        min_lb    = p['lookback'] + p['skip'] + 5
        available = [t for t in universe if t in prices.columns and t != 'SPY']
        ret_map   = {}

        for ticker in available:
            ts = prices[ticker].dropna()
            if len(ts) < min_lb:
                continue
            skip_end   = -(p['skip'] + 1)
            skip_start = -(p['lookback'] + p['skip'] + 1)
            p_end   = float(ts.iloc[skip_end])
            p_start = float(ts.iloc[skip_start])
            if p_start > 0:
                ret_map[ticker] = p_end / p_start - 1

        if not ret_map:
            return []

        s = pd.Series(ret_map)
        n = len(s)
        top_n = max(1, min(p['max_signals'], int(n * p['top_pct'])))
        top_tickers = s.nlargest(top_n).index.tolist()

        # ── Signal construction ───────────────────────────────────────────
        signals = []
        pos_size = round(0.10 * scale, 4)  # 10% per position, regime-scaled

        for ticker in top_tickers:
            ts      = prices[ticker].dropna()
            current = float(ts.iloc[-1])
            stops   = self.compute_stops_and_targets(ts, 'LONG', current)

            signals.append(Signal(
                ticker            = ticker,
                direction         = 'LONG',
                entry_price       = current,
                stop_loss         = stops['stop'],
                target_1          = stops['t1'],
                target_2          = stops['t2'],
                target_3          = stops['t3'],
                position_size_pct = pos_size,
                confidence        = 'MED',
                signal_params     = {
                    'momentum_return': round(float(ret_map.get(ticker, 0)), 4),
                    'spy_vs_fast_sma': round(spy_current / spy_fast - 1, 4),
                    'spy_fast_vs_slow': round(spy_fast / spy_slow - 1, 4),
                },
            ))

        return signals
