'use strict';

/**
 * signal-ledger.js — Persistent audit log for all trade signals generated by the desk.
 *
 * Storage: output/signals.json — append-only, never delete.
 * Signals expire after 7 days with no operator action (status → EXPIRED).
 *
 * Schema per signal:
 * {
 *   signal_id:            string  — e.g. "SIG-AAPL-20260405-001"
 *   ticker:               string
 *   generated:            ISO-8601 string
 *   signal_type:          "ENTRY_LONG" | "ENTRY_SHORT" | "EXIT" | "HOLD" | "AVOID"
 *   signal_strength:      1-10
 *   screener_output:      string  — raw screener block for this signal
 *   sizer_output:         string  — raw sizer block for this signal
 *   timer_output:         string  — raw timer block for this signal
 *   risk_output:          string  — raw risk block for this signal
 *   risk_verdict:         "APPROVED" | "APPROVED_WITH_CONDITIONS" | "REJECTED"
 *   reporter_output:      string  — final trade report
 *   status:               "PENDING_OPERATOR" | "EXECUTED" | "EXPIRED" | "REJECTED_BY_RISK" | "REJECTED_BY_OPERATOR"
 *   operator_action:      "BUY" | "PASS" | null
 *   operator_action_date: ISO-8601 | null
 *   notes:                string
 * }
 */

const fs   = require('fs');
const path = require('path');

const WORKDIR     = process.env.OPENCLAW_DIR || '/root/openclaw';
const LEDGER_FILE = path.join(WORKDIR, 'output', 'signals.json');
const EXPIRY_DAYS = 7;

// ── Internal helpers ──────────────────────────────────────────────────────────

function loadLedger() {
  try {
    if (!fs.existsSync(LEDGER_FILE)) return [];
    return JSON.parse(fs.readFileSync(LEDGER_FILE, 'utf8'));
  } catch {
    return [];
  }
}

function saveLedger(signals) {
  fs.mkdirSync(path.dirname(LEDGER_FILE), { recursive: true });
  fs.writeFileSync(LEDGER_FILE, JSON.stringify(signals, null, 2), 'utf8');
}

/** Generate signal ID: SIG-{TICKER}-{YYYYMMDD}-{NNN} */
function generateSignalId(ticker) {
  const date    = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  const signals = loadLedger().filter(s => s.signal_id.startsWith(`SIG-${ticker}-${date}`));
  const seq     = String(signals.length + 1).padStart(3, '0');
  return `SIG-${ticker}-${date}-${seq}`;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Add a new signal after the full pipeline completes.
 * Returns the signal ID.
 */
function addSignal(data) {
  const signals   = loadLedger();
  const signal_id = data.signal_id || generateSignalId(data.ticker);
  const signal    = {
    signal_id,
    ticker:               data.ticker,
    generated:            data.generated || new Date().toISOString(),
    signal_type:          data.signal_type || 'ENTRY_LONG',
    signal_strength:      data.signal_strength || 0,
    screener_output:      data.screener_output || '',
    sizer_output:         data.sizer_output    || '',
    timer_output:         data.timer_output    || '',
    risk_output:          data.risk_output     || '',
    risk_verdict:         data.risk_verdict    || 'PENDING',
    reporter_output:      data.reporter_output || '',
    status:               data.status          || 'PENDING_OPERATOR',
    operator_action:      null,
    operator_action_date: null,
    notes:                data.notes           || '',
  };
  signals.push(signal);
  saveLedger(signals);
  return signal_id;
}

/**
 * Update signal status when operator acts.
 * action: "BUY" | "PASS"
 * Returns true if found and updated, false otherwise.
 */
function operatorAction(signalId, action, notes = '') {
  const signals = loadLedger();
  const idx     = signals.findIndex(s => s.signal_id === signalId);
  if (idx === -1) return false;

  const status = action === 'BUY' ? 'EXECUTED' : 'REJECTED_BY_OPERATOR';
  signals[idx].operator_action      = action;
  signals[idx].operator_action_date = new Date().toISOString();
  signals[idx].status               = status;
  if (notes) signals[idx].notes = notes;

  saveLedger(signals);
  return true;
}

/**
 * Expire signals older than EXPIRY_DAYS with no operator action.
 * Returns count of expired signals.
 */
function expireStale() {
  const signals    = loadLedger();
  const cutoff     = Date.now() - EXPIRY_DAYS * 24 * 60 * 60 * 1000;
  let   expireCount = 0;

  signals.forEach(s => {
    if (s.status === 'PENDING_OPERATOR' && new Date(s.generated).getTime() < cutoff) {
      s.status = 'EXPIRED';
      expireCount++;
    }
  });

  if (expireCount > 0) saveLedger(signals);
  return expireCount;
}

/**
 * Get active (PENDING_OPERATOR) signals.
 */
function getActiveSignals() {
  expireStale(); // lazy expiry on read
  return loadLedger().filter(s => s.status === 'PENDING_OPERATOR');
}

/**
 * Get a single signal by ID.
 */
function getSignal(signalId) {
  return loadLedger().find(s => s.signal_id === signalId) || null;
}

/**
 * Get all signals for a ticker (any status).
 */
function getSignalsByTicker(ticker) {
  return loadLedger().filter(s => s.ticker === ticker.toUpperCase());
}

/**
 * Get signal summary for /status output.
 */
function getSummary() {
  expireStale();
  const signals = loadLedger();
  const counts  = {
    total:              signals.length,
    pending:            signals.filter(s => s.status === 'PENDING_OPERATOR').length,
    executed:           signals.filter(s => s.status === 'EXECUTED').length,
    rejected_by_risk:   signals.filter(s => s.status === 'REJECTED_BY_RISK').length,
    rejected_by_op:     signals.filter(s => s.status === 'REJECTED_BY_OPERATOR').length,
    expired:            signals.filter(s => s.status === 'EXPIRED').length,
  };
  return counts;
}

module.exports = { addSignal, operatorAction, expireStale, getActiveSignals, getSignal, getSignalsByTicker, getSummary, generateSignalId };
